# retrain-workflow.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retrain-workflow-
  namespace: mlflow
spec:
  entrypoint: retrain
  arguments:
    parameters:
    - name: data-dir
      value: "s3://minio/data/processed"
    - name: model-dir
      value: "s3://minio/models/best_model"

  templates:
  - name: retrain
    steps:
    - - name: prepare-data
        template: data-preparation
    - - name: retrain-model
        template: retrain-model
    - - name: evaluate-model
        template: evaluate-model

  - name: data-preparation
    container:
      image: measureapp/ml_job:0.0.6
      command: ["/bin/bash", "-c"]
      args:
        - |
          python /app/scripts/run_data_preparation.py --data-path /app/data/raw/telco_churn.csv --config-path /app/config/process.yaml --output-dir /app/data/processed

  - name: retrain-model
    container:
      image: measureapp/ml_job:0.0.6
      command: ["/bin/bash", "-c"]
      args:
        - |
          python /app/scripts/model_training.py

  - name: evaluate-model
    container:
      image: measureapp/ml_job:0.0.6
      command: ["/bin/bash", "-c"]
      args:
        - |
          python /app/scripts/evaluate_model.py