apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: drift-retrain-template
  namespace: argo-events
spec:
  entrypoint: retrain-workflow
  serviceAccountName: default
  arguments:
    parameters:
    - name: data-dir
      value: "s3://minio/data/app/data/processed"
    - name: model-dir
      value: "s3://minio/models/best_model"

  templates:
  - name: retrain-workflow
    inputs:
      parameters:
      - name: data-dir
      - name: model-dir
    steps:
    - - name: retrain-model
        template: retrain-model
        arguments:
          parameters:
          - name: data-dir
            value: "{{inputs.parameters.data-dir}}"
          - name: model-dir
            value: "{{inputs.parameters.model-dir}}"
    - - name: notify-reload
        template: notify-reload

  - name: retrain-model
    inputs:
      parameters:
      - name: data-dir
      - name: model-dir
    container:
      image: measureapp/ml_job:0.0.26
      imagePullPolicy: Always
      command: ["/bin/bash", "-c"]
      args:
        - |
          python /app/scripts/retrain_model.py
      env:
      - name: MINIO_URL
        value: "http://minio-service.minio.svc.cluster.local:9000"
      - name: AWS_ACCESS_KEY_ID
        value: "uaTJ6O0revHeQi0hcuXk"
      - name: AWS_SECRET_ACCESS_KEY
        value: "9PG7MDJrawCJ4MLdXYZdDbKNxZXoqwtpNhCfAkP3"
      imagePullSecrets:
      - name: docker-registry-creds

  - name: notify-reload
    inputs:
      parameters:
      - name: url
        value: "http://fastapi-service.fastapi.svc.cluster.local/reload-model"
    container:
      image: curlimages/curl:latest
      command: ["sh", "-c"]
      args:
        - |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"message": "Reload model after retrain", "timestamp": "{{workflow.creationTimestamp}}"}' \
            "{{inputs.parameters.url}}"



