apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: argo-events
imagePullSecrets:
  - name: docker-registry-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-service-account
  namespace: argo-events
imagePullSecrets:
  - name: docker-registry-creds
