apiVersion: batch/v1
kind: CronJob
metadata:
  name: drift-detection-job
  namespace: mlflow
spec:
  schedule: "*/10 * * * *"  # Every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: call-fastapi-drift-detection
            image: curlimages/curl:latest  # Use a lightweight image for HTTP requests
            command: ["sh", "-c"]
            args:
              - |
                curl -X POST -H "Content-Type: application/json" \
                http://fastapi-service.fastapi.svc.cluster.local/detect-drift
            env:
            - name: FASTAPI_URL
              value: "http://fastapi-service.fastapi.svc.cluster.local"  # FastAPI service URL
          restartPolicy: OnFailure
